"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

DEFAULT_CHARSET = "utf-8"
EMAIL_ALLOW_UNICODE = True

# 先に BASE_DIR を定義する
BASE_DIR = Path(__file__).resolve().parent.parent

# XXX.envを読み込む
load_dotenv()

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")  # これが /home/***/prod/static に相当

# os.getenv で環境変数から取得する
SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG") == "True"
SERVER_IP = os.getenv("SERVER_IP")
DOMEIN = os.getenv("DOMEIN")
csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if csrf_origins:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins.split(",")]
else:
    print(f"--- DEBUG: CSRF_TRUSTED_ORIGINS ENV READ ERROR ---")
print(f"--- DEBUG: CSRF_TRUSTED_ORIGINS is {CSRF_TRUSTED_ORIGINS} ---")
print(f"--- DEBUG: DOMEIN is [{DOMEIN}] ---")

ALLOWED_HOSTS = [
    SERVER_IP,
    "127.0.0.1",
    "localhost",
    DOMEIN,
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    "board",  # 自分のアプリが最優先
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "board.context_processors.const_settings",
                "board.context_processors.environment_info",
                "board.context_processors.support_widget",
                "board.context_processors.site_config",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database 環境変数
SQL_PASSWORD = os.getenv("SQL_PASSWORD")
SQL_HOST = os.environ.get("SQL_HOST", "127.0.0.1")
SQL_DB_NAME = os.environ.get("SQL_DB_NAME")
SQL_USER = os.environ.get("SQL_USER")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": SQL_DB_NAME,
        "USER": SQL_USER,
        "PASSWORD": SQL_PASSWORD,
        "HOST": SQL_HOST,
        "PORT": "5432",
        "CONN_MAX_AGE": 60,  # 接続を使い回して高速化
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ja"
# LANGUAGE_CODE = "en-us"  # For debug (パスワードリセットメールのbase64対応)

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True

LOGOUT_ON_GET = True

APPEND_SLASH = True

# セッションタイムアウト
SESSION_COOKIE_AGE = 1800  # 秒
SESSION_SAVE_EVERY_REQUEST = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "board", "static"),
]

# ログインが必要な時に飛ばす先のURL名（name="login" に対応）
LOGIN_URL = "login"
# ログイン成功時のリダイレクト先（掲示板トップ）
LOGIN_REDIRECT_URL = "index"

# ログアウト後のリダイレクト先（掲示板トップ）
LOGOUT_REDIRECT_URL = "login"

# Mailを使ったユーザー登録、パスワードリセット
# 本番（Gmailなど）を使う場合はここを SMTP 設定に書き換えます
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # ターミナルに表示

# --- 本番（OCI運用時）に設定すべき内容（例：GmailやSendGridなど） ---
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_REGISTER_MESSAGE = os.getenv("EMAIL_REGISTER_MESSAGE", "掲示板")
