# Generated by Django 6.0.3 on 2026-03-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='aauthor',
            new_name='author',
        ),
    ]
