# Generated by Django 6.0.3 on 2026-03-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_post_title_post_cast_name_post_cast_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='訪問日'),
        ),
    ]
