# Generated by Django 6.0.3 on 2026-03-24 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_point_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
