# Generated by Django 6.0.3 on 2026-03-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_profile_last_point_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='ニックネーム'),
        ),
    ]
