# Generated by Django 6.0.3 on 2026-04-04 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_postreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', verbose_name='感想'),
        ),
        migrations.AlterField(
            model_name='post',
            name='stars',
            field=models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='評価'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visit_date',
            field=models.DateField(null=True, verbose_name='訪問日'),
        ),
    ]
