# Generated by Django 6.0.3 on 2026-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_post_content_alter_post_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
