# Generated by Django 6.0.3 on 2026-04-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0013_post_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="", max_length=50, verbose_name="カテゴリ"),
        ),
    ]
