# Generated by Django 6.0.3 on 2026-04-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.CharField(default='', max_length=50, verbose_name='地域'),
        ),
    ]
