# Generated by Django 6.0.3 on 2026-04-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_post_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='first_name',
        ),
    ]
