# Generated by Django 6.0.3 on 2026-04-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_rename_nickname_profile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
