# Generated by Django 6.0.3 on 2026-04-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_remove_profile_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_locked', models.BooleanField(default=False, verbose_name='新規登録をロックする')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='メンテナンス中メッセージ')),
            ],
            options={
                'verbose_name': 'システム設定',
                'verbose_name_plural': 'システム設定',
            },
        ),
    ]
