# Generated by Django 6.0.3 on 2026-04-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='login_locked',
            field=models.BooleanField(default=False, verbose_name='ログインをロックする（管理者以外）'),
        ),
    ]
