# Generated by Django 6.0.3 on 2026-04-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_siteconfig_login_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地域'),
        ),
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.CharField(default='', max_length=50, verbose_name='都道府県'),
        ),
    ]
