# Generated by Django 6.0.3 on 2026-04-30 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_information_alter_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_point_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
