# Generated by Django 6.0.3 on 2026-05-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_alter_profile_last_point_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
